import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))

const EXCLUDED_DIRS = new Set([
  '.vitepress',
  '.github',
  '.git',
  'node_modules',
])
const EXCLUDED_FILES = new Set(['README.md', 'CLAUDE.md', 'INDEX.md', 'index.md'])

// 48 个一级目录的中文名
export const TOP_DIR_LABELS: Record<string, string> = {
  'acs-v1': '智能门禁',
  'admin-v1': '管理后台',
  'ai': 'AI 能力',
  'aily-v1': '智能伙伴 Aily',
  'apaas-v1': '低代码 aPaaS',
  'api-call-guide': 'API 调用指南',
  'application-v6': '应用信息',
  'approval-v4': '审批',
  'attendance-v1': '考勤打卡',
  'authentication-management': '身份验证管理',
  'bot-v3': '机器人',
  'calendar-v4': '日历',
  'cardkit-v1': '卡片组件',
  'contact-v3': '通讯录',
  'corehr-v1': '飞书人事',
  'directory-v1': '组织架构',
  'ehr-v1': '智能 HR',
  'elearning-v2': '在线学习',
  'event-subscription-guide': '事件订阅指南',
  'group': '群组',
  'helpdesk-v1': '服务台',
  'hire-v1': '招聘',
  'historic-version': '历史版本',
  'human_authentication-v1': '实名认证',
  'im-v1': '即时消息 v1',
  'im-v2': '即时消息 v2',
  'lingo-v1': '词典',
  'mail-v1': '邮箱',
  'mdm-v1': '主数据',
  'minutes-v1': '妙记',
  'moments-v1': '公司圈',
  'okr-v1': 'OKR',
  'payroll-v1': '飞书薪酬',
  'performance-v1': '飞书绩效',
  'personal_settings-v1': '个人设置',
  'report-v1': '汇报',
  'search-v2': '搜索',
  'security_and_compliance-v1': '安全合规',
  'server-side-sdk': '服务端 SDK',
  'spark-v1': '多维表格',
  'task-v2': '任务',
  'tenant-tag': '租户标签',
  'tenant-v2': '企业信息',
  'trust_party-v1': '互通群',
  'uUDN04SN0QjL1QDN': '云文档',
  'vc-v1': '视频会议',
  'verification-v1': '认证服务',
  'workplace-v1': '工作台',
}

// 常见子目录（资源/对象名）的中文映射
const SUBDIR_LABELS: Record<string, string> = {
  'access_record': '门禁记录',
  'access-record': '门禁记录',
  'access_token': '访问令牌',
  'announcement': '公告',
  'app': '应用',
  'app-storage': '应用存储',
  'app-table': '数据表',
  'app-table-record': '记录',
  'app-view': '视图',
  'app-enum': '枚举',
  'application': '应用',
  'approval': '审批',
  'approval_groups': '审批组',
  'archive_rule': '归档规则',
  'attachment': '附件',
  'audit_log': '审计日志',
  'badge': '徽章',
  'badge-image': '徽章图片',
  'bitable': '多维表格',
  'block': '块',
  'blocks': '块',
  'board': '画板',
  'bot': '机器人',
  'CalendarAPI': '日历 API',
  'calendar': '日历',
  'calendar-acl': '日历访问控制',
  'calendar-event': '日程',
  'calendar-event-attendee': '日程参与人',
  'calendar-event-meeting_chat': '日程群聊',
  'candidate': '候选人',
  'card': '卡片',
  'chat': '群聊',
  'chats': '群聊',
  'chat-announcement': '群公告',
  'chat-announcement-block': '群公告块',
  'chat-managers': '群管理员',
  'chat-members': '群成员',
  'chat-tab': '群标签页',
  'chat-top_notice': '群置顶通知',
  'comment': '评论',
  'CommentAPI': '评论 API',
  'common-event': '通用事件',
  'common': '通用',
  'company': '公司',
  'compensation_standard': '薪资标准',
  'contract': '合同',
  'conversation': '会话',
  'corehr': '人事',
  'cost_center': '成本中心',
  'country': '国家',
  'country_region': '国家地区',
  'currency': '货币',
  'custom_attr': '自定义字段',
  'custom_field': '自定义字段',
  'data': '数据',
  'department': '部门',
  'department-job_family': '部门岗位族',
  'departments': '部门',
  'development-guide': '开发指南',
  'device': '设备',
  'directory': '目录',
  'directory-user': '目录用户',
  'docs-v1': '文档 v1',
  'docs': '云文档',
  'docx': '新版文档',
  'document': '文档',
  'document-block': '文档块',
  'document-block-children': '文档块子节点',
  'draft': '草稿',
  'drafts': '草稿',
  'drive': '云空间',
  'drive-v1': '云空间 v1',
  'email-alias': '邮箱别名',
  'employee': '员工',
  'employee-custom_org': '员工自定义组织',
  'employees': '员工',
  'employees-bp': '员工 BP',
  'employees-job_data': '员工职位数据',
  'employment': '雇佣',
  'enum': '枚举',
  'event': '事件',
  'events': '事件',
  'exam': '考试',
  'export': '导出',
  'export_task': '导出任务',
  'ext_account': '外部账号',
  'external_instance': '外部实例',
  'external_task': '外部任务',
  'faq': '常见问题',
  'feed': 'Feed 流',
  'feedback': '反馈',
  'field': '字段',
  'file': '文件',
  'files': '文件',
  'file_comment': '文档评论',
  'file-comment': '文档评论',
  'file-statistics': '文件统计',
  'file-version': '文件版本',
  'file-view-record': '文件浏览记录',
  'flag': '收藏',
  'folder': '文件夹',
  'form': '表单',
  'function-list': '功能列表',
  'general-modules': '通用模块',
  'group': '用户组',
  'helpdesk': '服务台',
  'hire': '招聘',
  'holiday': '节假日',
  'home': '首页',
  'image': '图片',
  'images': '图片',
  'import': '导入',
  'import_task': '导入任务',
  'instance': '实例',
  'interview': '面试',
  'invoice': '发票',
  'iframe': '嵌入',
  'IM': '即时消息',
  'IM-v2': '即时消息 v2',
  'job-management': '岗位管理',
  'job_change': '人员异动',
  'job_data': '职位数据',
  'job_family': '序列',
  'job_level': '职级',
  'job_title': '职称',
  'knowledge_space': '知识空间',
  'knowledge-space': '知识空间',
  'label': '标签',
  'leave': '假勤',
  'leave_accrual_record': '假期发放记录',
  'leave_employ_expire_record': '假期失效记录',
  'log_collect': '日志收集',
  'mail-attachment': '邮件附件',
  'mail-content': '邮件内容',
  'mail-rule': '邮件规则',
  'mailbox': '邮箱',
  'mailbox-folder': '邮箱文件夹',
  'mailgroup': '邮件组',
  'meeting': '会议',
  'meeting-recording': '会议录制',
  'meeting_room': '会议室',
  'meeting_room-list': '会议室列表',
  'member': '成员',
  'members': '成员',
  'message': '消息',
  'message-card': '消息卡片',
  'message-content': '消息内容',
  'message-reaction': '消息表情',
  'message-resource': '消息资源',
  'messages': '消息',
  'minute': '妙记',
  'moments': '公司圈',
  'node': '节点',
  'note': '笔记',
  'notes': '笔记',
  'offer': 'Offer',
  'okr': 'OKR',
  'okr-v1': 'OKR v1',
  'organization': '组织',
  'organization-management': '组织管理',
  'overview': '概述',
  'page': '页面',
  'patch': '更新',
  'payroll': '薪酬',
  'people': '人员',
  'performance': '绩效',
  'permission': '权限',
  'permissions': '权限',
  'pin': 'Pin',
  'platform': '平台',
  'position': '岗位',
  'post': '帖子',
  'pre_hire': '待入职',
  'probation': '试用期',
  'progress': '进度',
  'public_mailbox': '公共邮箱',
  'public_mailbox-member': '公共邮箱成员',
  'quote': '引用',
  'range_setting': '范围设置',
  'reaction': '表情回应',
  'record': '记录',
  'records': '记录',
  'recruitment': '招聘',
  'rejected_application': '被拒申请',
  'reference': '参考',
  'reference_check': '背景调查',
  'relation': '关系',
  'relationship': '关系',
  'report': '汇报',
  'request': '请求',
  'response': '响应',
  'review': '评审',
  'role': '角色',
  'room': '会议室',
  'rule': '规则',
  'rules': '规则',
  'rule_external': '外部规则',
  'schedule': '日程',
  'scope': '权限',
  'scope-list': '权限列表',
  'scopes': '权限',
  'search': '搜索',
  'search_wiki': '搜索知识库',
  'server-api-list': 'API 列表',
  'session': '会话',
  'setting': '设置',
  'settings': '设置',
  'shared': '共享',
  'sheet': '工作表',
  'sheet-filter': '表格筛选',
  'sheet-filter-view': '筛选视图',
  'sheet-filter-view-condition': '筛选视图条件',
  'sheet-imageRange': '图片范围',
  'sheets-v3': '电子表格 v3',
  'shift': '班次',
  'siganture': '电子签',
  'signature': '电子签',
  'signature_file': '电子签文件',
  'signature_template': '电子签模板',
  'skill': '技能',
  'spreadsheet': '电子表格',
  'spreadsheet-sheet': '工作表',
  'spreadsheet-sheet-filter': '表格筛选',
  'spreadsheet-sheet-float_image': '浮动图片',
  'sso': 'SSO',
  'subject': '主题',
  'subscription': '订阅',
  'subscribe': '订阅',
  'subscriptions': '订阅',
  'tag': '标签',
  'tags': '标签',
  'talent': '人才',
  'talent_pool': '人才库',
  'task': '任务',
  'tasks': '任务',
  'tasklist': '清单',
  'template': '模板',
  'templates': '模板',
  'thread': '话题',
  'ticket': '工单',
  'tickets': '工单',
  'todo': '待办',
  'token': '令牌',
  'training': '培训',
  'type': '类型',
  'unit': '单位',
  'update': '更新',
  'user': '用户',
  'users': '用户',
  'user_approval': '用户假勤',
  'user_daily_shift': '用户每日班次',
  'user_mailbox': '用户邮箱',
  'user_mailbox-attachment': '用户邮件附件',
  'user_mailbox-contact': '用户邮箱联系人',
  'user_mailbox-draft': '用户邮件草稿',
  'user_mailbox-event': '用户邮箱事件',
  'user_mailbox-folder': '用户邮件文件夹',
  'user_mailbox-label': '用户邮件标签',
  'user_mailbox-mail_contact': '用户邮件联系人',
  'user_mailbox-message': '用户邮件',
  'user_mailbox-rule': '用户邮件规则',
  'user_mailbox-setting': '用户邮箱设置',
  'user_mailbox-template': '用户邮件模板',
  'user_mailbox-thread': '用户邮件会话',
  'user_migration': '用户迁移',
  'user_setting': '用户设置',
  'user_stats_data': '用户统计数据',
  'user_stats_field': '用户统计字段',
  'user_stats_view': '用户统计视图',
  'user-face': '用户人脸',
  'view': '视图',
  'views': '视图',
  'visitor': '访客',
  'vendor': '供应商',
  'video_conferencing': '视频会议',
  'webhook': 'Webhook',
  'wiki': '知识库',
  'wiki-v2': '知识库 v2',
  'workplace': '工作台',
  'work_city': '工作城市',
  'work_data': '工作数据',

  // 补充 ~ 高频缺项
  'access-token': '访问令牌',
  'account': '账户',
  'acct_item': '薪资项',
  'activity': '活动',
  'admin': '管理',
  'advanced-permission': '高级权限',
  'agent': '客服',
  'agent_skill': '客服技能',
  'agent_skill_rule': '客服技能规则',
  'agent-function': '客服功能',
  'agent-schedules': '客服排班',
  'aily_session': 'Aily 会话',
  'aily_session-aily_message': 'Aily 会话消息',
  'aily_session-run': 'Aily 运行',
  'alert': '告警',
  'apaas-v3': 'aPaaS v3',
  'app_badge': '应用徽章',
  'app_feed_card': '应用 Feed 卡片',
  'app_recommend_rule': '推荐规则',
  'app-administrator': '应用管理员',
  'app-block_workflow': '应用工作流',
  'app-dashboard': '应用仪表盘',
  'app-information': '应用信息',
  'app-role': '应用角色',
  'app-role-member': '应用角色成员',
  'app-skill': '应用技能',
  'app-table-field': '数据表字段',
  'app-table-field_group': '数据表字段分组',
  'app-table-view': '数据表视图',
  'app-workflow': '应用工作流',
  'archive': '归档',
  'auth': '认证',
  'auth-v4': '认证 v4',
  'authen': '认证',
  'authorization': '授权',
  'badge-grant': '徽章发放',
  'baike-v1': '百科 v1',
  'bank_card': '银行卡',
  'base': '基础',
  'basic-data': '基础数据',
  'basic-infomation': '基础信息',
  'batch_message': '批量消息',
  'bitable-v1': '多维表格 v1',
  'board-v1': '画板 v1',
  'business_card': '名片',
  'business_license': '营业执照',
  'callback-subscription': '回调订阅',
  'candidate-management': '候选人管理',
  'card-element': '卡片元素',
  'category': '分类',
  'chat-member': '群成员',
  'chat-menu_tree': '群菜单树',
  'chinese_passport': '中国护照',
  'choose-a-subscription-mode': '选择订阅方式',
  'classification': '分类',
  'conditionformat': '条件格式',
  'content': '内容',
  'cost_allocation': '成本分摊',
  'cost_allocation_detail': '成本分摊明细',
  'cost_allocation_plan': '成本分摊计划',
  'cost_allocation_report': '成本分摊报告',
  'course_registration': '课程注册',
  'currency-information': '货币信息',
  'custom_field-option': '自定义字段选项',
  'custom_org': '自定义组织',
  'data_source': '数据源',
  'data_source-item': '数据源项',
  'datasource': '数据源',
  'datasource_record': '数据源记录',
  'datavalidation': '数据校验',
  'default_cost_center': '默认成本中心',
  'device_apply_record': '设备申请记录',
  'device_record': '设备记录',
  'district': '行政区',
  'doc_wiki': '文档 / 知识库',
  'docs-assistant': '文档助手',
  'document_ai-v1': '文档 AI v1',
  'docx-v1': '新版文档 v1',
  'driving_license': '驾驶证',
  'employee_type': '员工类型',
  'employee_type_enum': '员工类型枚举',
  'employees-additional_job': '员工兼职',
  'employees-international_assignment': '员工国际派遣',
  'entity': '实体',
  'evaluation': '评估',
  'event-interface': '事件接口',
  'event-subscription-configure-': '事件订阅配置',
  'event-subscriptions': '事件订阅',
  'exchange_binding': 'Exchange 绑定',
  'external_approval': '外部审批',
  'external-talent': '外部人才',
  'faq-management': 'FAQ 管理',
  'feishu-native-approval': '飞书原生审批',
  'feishu-people': '飞书人事',
  'feishu-store-app-integration': '应用商店集成',
  'file-subscription': '文件订阅',
  'flow': '流程',
  'food_manage_license': '食品经营许可证',
  'food_produce_license': '食品生产许可证',
  'functional_role': '角色',
  'functional_role-member': '角色成员',
  'get-candidates': '获取候选人',
  'golang-sdk-guide': 'Go SDK 指南',
  'group-member': '用户组成员',
  'groups-bots': '群组与机器人',
  'health_certificate': '健康证',
  'hire_internal': '招聘内部',
  'historical_version': '历史版本',
  'hkm_mainland_travel_permit': '港澳通行证',
  'id_card': '身份证',
  'instance-comment': '实例评论',
  'interview-settings': '面试设置',
  'interviewer': '面试官',
  'introduction': '简介',
  'java-sdk-guide': 'Java SDK 指南',
  'job': '职位',
  'job_grade': '职级',
  'job_process': '职位流程',
  'job_requirement': '招聘需求',
  'job-change-events': '异动事件',
  'job-data-events': '职位数据事件',
  'like': '点赞',
  'list': '列表',
  'location': '地点',
  'location_data': '地点数据',
  'login-state-management': '登录态管理',
  'lump_sum_payment': '一次性支付',
  'mail-group': '邮件组',
  'mailgroup-alias': '邮件组别名',
  'mailgroup-manager': '邮件组管理员',
  'mailgroup-member': '邮件组成员',
  'mailgroup-permission_member': '邮件组权限成员',
  'mdm-v3': '主数据 v3',
  'media': '媒体',
  'meeting_room-v1': '会议室 v1',
  'meeting-room-data': '会议室数据',
  'meeting-room-event': '会议室事件',
  'message-content-description': '消息内容描述',
  'metric_detail': '指标详情',
  'metric_template': '指标模板',
  'minute-media': '妙记媒体',
  'minute-statistics': '妙记统计',
  'minute-transcript': '妙记文本',
  'national_id_type': '国家身份证类型',
  'nodejs-sdk': 'Node.js SDK',
  'notification': '通知',
  'offboarding': '离职',
  'offer_application_form': 'Offer 申请表',
  'offer_approval_template': 'Offer 审批模板',
  'offer-settings': 'Offer 设置',
  'onboard': '入职',
  'onboarding-qr-code': '入职二维码',
  'open-search': '开放搜索',
  'openapi_log': 'OpenAPI 日志',
  'optical_char_recognition-v1': 'OCR v1',
  'password': '密码',
  'pathway': '路径',
  'paygroup': '薪资组',
  'payment_activity': '支付活动',
  'payment_detail': '支付明细',
  'period': '周期',
  'period_rule': '周期规则',
  'permission-member': '权限成员',
  'permission-public': '公共权限',
  'permission-public-password': '公共权限密码',
  'person': '人员',
  'personal-information': '个人信息',
  'plan': '计划',
  'portal_apply_schema': '门户申请表单',
  'post_statistics': '帖子统计',
  'pre-hire': '待入职',
  'pre-hire-events': '待入职事件',
  'probation-events': '试用期事件',
  'process': '流程',
  'process-form_variable_data': '流程表单变量数据',
  'process-instance': '流程实例',
  'progress_record': '进度记录',
  'protect-range': '保护范围',
  'public-mailbox': '公共邮箱',
  'public_mailbox-alias': '公共邮箱别名',
  'python--sdk': 'Python SDK',
  'recurring_payment': '定期支付',
  'referral': '内推',
  'referral_account': '内推账户',
  'repo': '代码库',
  'reserve': '预订',
  'resignation-events': '离职事件',
  'resume': '简历',
  'resume_source': '简历来源',
  'review_config': '评审配置',
  'review_data': '评审数据',
  'review_template': '评审模板',
  'reviewee': '被评审者',
  'room_config': '会议室配置',
  'room_level': '会议室级别',
  'rule-view': '规则视图',
  'schema': '架构',
  'scope_config': '权限配置',
  'seat_activity': '席位活动',
  'seat_assignment': '席位分配',
  'section': '章节',
  'security_and_compliance-v2': '安全合规 v2',
  'semester': '学期',
  'semester_activity': '学期活动',
  'sheet-operation': '表格操作',
  'sheet-rowcol': '表格行列',
  'sheets': '表格',
  'social_archive': '社保档案',
  'social_insurance': '社保',
  'social_plan': '社保方案',
  'space': '空间',
  'space-member': '空间成员',
  'space-node': '空间节点',
  'space-setting': '空间设置',
  'special-event': '特殊事件',
  'speech_to_text-v1': '语音转文字 v1',
  'spreadsheet-sheet-filter_view': '筛选视图',
  'spreadsheet-sheet-filter_view-condition': '筛选视图条件',
  'stage_task': '阶段任务',
  'suite-search': '套件搜索',
  'system_status': '系统状态',
  'task-collaborator': '任务协作者',
  'task-comment': '任务评论',
  'task-follower': '任务关注者',
  'task-reminder': '任务提醒',
  'task-subtask': '子任务',
  'task-v1': '任务 v1',
  'tasklist-activity_subscription': '清单活动订阅',
  'taxi_invoice': '出租车发票',
  'tenant-product_assign_info': '租户产品分配',
  'third-party-approval-integration': '第三方审批集成',
  'ticket_customized_field': '工单自定义字段',
  'ticket-management': '工单管理',
  'ticket-message': '工单消息',
  'timeoff_event': '请假事件',
  'train_invoice': '火车票发票',
  'translation-v1': '翻译 v1',
  'tripartite_agreement': '三方协议',
  'tw_mainland_travel_permit': '台湾通行证',
  'upgraded-group-announcement': '升级版群公告',
  'upload': '上传',
  'url_preview': 'URL 预览',
  'user_auth_data_relation': '用户认证数据关系',
  'user_group_user_rel': '用户组用户关系',
  'user_mailbox-alias': '用户邮箱别名',
  'user_mailbox-message-attachment': '用户邮件附件',
  'user_task': '用户任务',
  'user_task_remedy': '用户任务补救',
  'user-task': '用户任务',
  'vat_invoice': '增值税发票',
  'vehicle_invoice': '车辆发票',
  'vehicle_license': '车辆牌照',
  'website': '网站',
  'whiteboard': '画板',
  'whiteboard-node': '画板节点',
  'workforce_plan': '人力计划',
  'working_hours_type': '工时类型',
  'workplace_access_data': '工作台访问数据',
  'workspace': '工作空间',
  'workspace-enum': '工作空间枚举',
  'workspace-table': '工作空间数据表',
  'workspace-view': '工作空间视图',
}

interface SidebarItem {
  text: string
  link?: string
  items?: SidebarItem[]
  collapsed?: boolean
}

function labelFor(name: string): string {
  // 直接命中字典
  if (SUBDIR_LABELS[name]) return SUBDIR_LABELS[name]
  // 复合名（dash 分隔）：每段查字典，至少一段命中就用 - 拼回
  if (name.includes('-')) {
    const parts = name.split('-').filter(Boolean)
    const translated = parts.map((p) => SUBDIR_LABELS[p] ?? p)
    if (translated.some((t, i) => t !== parts[i])) {
      return translated.join(' · ')
    }
  }
  return name
}

function extractTitle(filePath: string): string {
  try {
    const head = readFileSync(filePath, 'utf-8').slice(0, 2048)
    const fm = head.match(/^title:\s*"((?:[^"\\]|\\.)*)"/m)
    if (fm) return fm[1].replace(/\\"/g, '"').trim()
    const h1 = head.match(/^# (.+)$/m)
    if (h1) return h1[1].trim()
  } catch {
    /* fall through */
  }
  return filePath.split('/').pop()!.replace(/\.md$/, '')
}

function scanDir(dirPath: string): SidebarItem[] {
  let entries: string[] = []
  try {
    entries = readdirSync(dirPath)
  } catch {
    return []
  }

  const dirs: { name: string; full: string }[] = []
  const files: { name: string; full: string }[] = []

  for (const name of entries) {
    if (name.startsWith('.') || EXCLUDED_DIRS.has(name)) continue
    const full = join(dirPath, name)
    let stat
    try {
      stat = statSync(full)
    } catch {
      continue
    }
    if (stat.isDirectory()) {
      dirs.push({ name, full })
    } else if (name.endsWith('.md') && !EXCLUDED_FILES.has(name)) {
      files.push({ name, full })
    }
  }

  files.sort((a, b) => a.name.localeCompare(b.name))
  dirs.sort((a, b) => a.name.localeCompare(b.name))

  const out: SidebarItem[] = []
  for (const f of files) {
    out.push({
      text: extractTitle(f.full),
      link: '/' + relative(ROOT, f.full).replace(/\.md$/, '').replace(/\\/g, '/'),
    })
  }
  for (const d of dirs) {
    const items = scanDir(d.full)
    if (items.length > 0) {
      out.push({ text: labelFor(d.name), items, collapsed: true })
    }
  }
  return out
}

function findFirstLink(items: SidebarItem[]): string | undefined {
  for (const it of items) {
    if (it.link) return it.link
    if (it.items) {
      const sub = findFirstLink(it.items)
      if (sub) return sub
    }
  }
  return undefined
}

export function topLevelDirs(): string[] {
  return readdirSync(ROOT)
    .filter((n) => !n.startsWith('.') && !EXCLUDED_DIRS.has(n))
    .filter((n) => {
      try {
        return statSync(join(ROOT, n)).isDirectory()
      } catch {
        return false
      }
    })
    .sort((a, b) => a.localeCompare(b))
}

export function generateSidebar(): Record<string, SidebarItem[]> {
  const sidebar: Record<string, SidebarItem[]> = {}
  for (const dir of topLevelDirs()) {
    const items = scanDir(join(ROOT, dir))
    sidebar[`/${dir}/`] = [
      { text: TOP_DIR_LABELS[dir] ?? dir, items, collapsed: false },
    ]
  }
  return sidebar
}

// 给 nav / index features 用：每个一级目录的"首篇文档"链接
export function firstDocLinks(): Record<string, string> {
  const map: Record<string, string> = {}
  const sidebar = generateSidebar()
  for (const key of Object.keys(sidebar)) {
    const link = findFirstLink(sidebar[key])
    if (link) map[key.replace(/^\/|\/$/g, '')] = link
  }
  return map
}
